### GET request get all users
GET http://localhost:3000/api/users
Accept: application/json

### GET request single user
#TODO Not working with generated UUID
GET http://localhost:3000/api/users/71dd4c67-523b-4ddd-a180-e18f6d01af6a
Accept: application/json

### Send POST request with json body
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Loui"
}

### Delete request single user
DELETE http://localhost:3000/api/users/71dd4c67-523b-4ddd-a180-e18f6d01af6a
Accept: application/json









